
cache:
  directories:
    - ${HOME}/debs

jobs:
  # linux native build
  - name: "Linux native"
    os: linux
    compiler: gcc
    dist: bionic
    env:
      - TARGET="linux"
    services:
      - xvfb

before_install:
  - bash ${TRAVIS_BUILD_DIR}/.travis/before_install.sh

install:
  - bash ${TRAVIS_BUILD_DIR}/.travis/install.sh

script:
  - make
  - make -C tests
