
cache:
  directories:
    - ${HOME}/debs

jobs:
  - name: "Linux native"
    os: linux
    compiler: gcc
    dist: bionic
    env:
      - TARGET="linux"
    services:
      - xvfb
    script:
      - sh ${TRAVIS_BUILD_DIR}/.travis/script-linux.sh

  #- name: "win32 cross-compilation"
    #os: linux
    #compiler: gcc
    #dist: bionic
    #env:
      #- TARGET="win32"
    #services:
      #- xvfb
    #script:
      #- sh ${TRAVIS_BUILD_DIR}/.travis/script-win32.sh

  #- name: "win64 cross-compilation"
    #os: linux
    #compiler: gcc
    #dist: bionic
    #env:
      #- TARGET="win32"
    #services:
      #- xvfb
    #script:
      #- sh ${TRAVIS_BUILD_DIR}/.travis/script-win64.sh

before_install:
  - bash ${TRAVIS_BUILD_DIR}/.travis/before_install.sh

install:
  - bash ${TRAVIS_BUILD_DIR}/.travis/install.sh
