language: cpp

env:
  global:
    - MAKEFLAGS="-j 2"

addons:
  apt:
    packages:
      - autopoint
      - dssi-dev
      - intltool
      - libasound-dev
      - libgtk2.0-dev
      - libjack-jackd2-dev
      - liblash-compat-dev
      - liblo-dev
      - liboscpack-dev
      - pandoc

install:
  - pip install --user cpp-coveralls

jobs:
  include:
    - os: linux
      dist: precise
      name: "Build (Ubuntu Precise 12.04 / GCC 4.6.3)"
      compiler: gcc
      script: ./autogen.sh && ./configure && make V=1 distcheck
    - os: linux
      dist: trusty
      name: "Test (Ubuntu Trusty 14.04 / GCC 4.8.4)"
      compiler: gcc
      script: ./autogen.sh && ./configure --without-gui CFLAGS='-O0 -g -fprofile-arcs -ftest-coverage' && make V=1 check
        # && coveralls --gcov-options '\-lp' -e config.h -e include -e src/drivers -e src/GUI -e utils
