language: cpp

env:
  global:
    - MAKEFLAGS="-j 2"

addons:
  apt:
    packages:
      - autoconf-archive
      - autopoint
      - dssi-dev
      - intltool
      - libasound-dev
      - libgtk2.0-dev
      - libjack-jackd2-dev
      - liblash-compat-dev
      - liblo-dev
      - pandoc

install:
  - pip install --user cpp-coveralls

jobs:
  include:
    - os: linux
      dist: xenial
      name: "Test (Ubuntu Xenial 16.04 / GCC 5.4.0)"
      compiler: gcc
      script: ./autogen.sh && ./configure --without-gui CFLAGS='-O0 -g -fprofile-arcs -ftest-coverage' && make V=1 check
        # && coveralls --gcov-options '\-lp' -e config.h -e include -e src/drivers -e src/GUI -e utils
