name: irc

on: [push]

jobs:
  notification:
    runs-on: ubuntu-latest
    name: IRC notification
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ github.event.head_commit.message }}
          separator: '\n'
          maxsplit: 1
      - name: IRC notification
        uses: Gottox/irc-message-action@v2
        with:
          channel: '#kxstudio'
          nickname: kxstudio-bot
          message: |-
            ${{ github.actor }} pushed ${{ steps.split.outputs._0 }} ${{ github.event.compare }}
