name: Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        sudo apt install autopoint dssi-dev intltool libasound-dev libgtk2.0-dev libjack-jackd2-dev liblash-compat-dev liblo-dev liboscpack-dev pandoc
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure CFLAGS='-O0 -g -fprofile-arcs -ftest-coverage'
    - name: make distcheck
      run: make -j 2 distcheck
    - name: Codecov
      uses: codecov/codecov-action@v1.0.4
      with:
        token: f7bd75a9-026b-4157-9f6e-708d6149d979
