name: Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: sudo apt install autopoint dssi-dev intltool libasound-dev libgtk2.0-dev libjack-jackd2-dev liblo-dev pandoc
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make distcheck
      run: make -j 2 distcheck
    - name: Test
      run: |
        ./configure CFLAGS='-O0 -g -fprofile-arcs -ftest-coverage' --without-lv2 --without-dssi --without-vst
        make -j 2 check
        gcov -lp $(find . -name '*.c' -o -name '*.cpp')
    - name: Codecov
      uses: codecov/codecov-action@v1.0.4
      with:
        token: f7bd75a9-026b-4157-9f6e-708d6149d979
